server:
  address: 127.0.0.1
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easyexcel_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 200
      max-idle: 9
    username: root
    password: 97108lymysql
  thymeleaf:
    enabled: true  #\u5F00\u542Fthymeleaf\u89C6\u56FE\u89E3\u6790
    encoding: utf-8  #\u7F16\u7801
    prefix: classpath:/templates/  #\u524D\u7F00
    cache: false  #\u662F\u5426\u4F7F\u7528\u7F13\u5B58
    mode: HTML  #\u4E25\u683C\u7684HTML\u8BED\u6CD5\u6A21\u5F0F
    suffix: .html  #\u540E\u7F00\u540D
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: link.lycreate.springbooteasyexceldemo.domain
